# Generated by Django 6.1.1 on 2026-09-12 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=64)),
                ('input_text', models.TextField()),
                ('predicted_intent', models.CharField(blank=True, max_length=64)),
                ('intent_confidence', models.FloatField(blank=True, null=True)),
                ('grounding_thread_ids', models.JSONField(blank=True, default=list)),
                ('drafted_reply', models.TextField(blank=True)),
                ('escalate', models.BooleanField(default=False)),
                ('escalation_reason', models.TextField(blank=True)),
                ('judge_score', models.FloatField(blank=True, null=True)),
                ('judge_rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoldenExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=64)),
                ('message_text', models.TextField()),
                ('should_escalate', models.BooleanField()),
                ('escalation_reason', models.TextField(blank=True)),
                ('ideal_reply_notes', models.TextField(blank=True, help_text='What a good reply must contain/avoid.')),
                ('sampling_note', models.CharField(blank=True, help_text='Why/how this example was chosen.', max_length=255)),
                ('true_intent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supportagent.intent')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=32, unique=True)),
                ('author_id', models.CharField(max_length=64)),
                ('brand', models.CharField(db_index=True, max_length=64)),
                ('text', models.TextField()),
                ('is_from_company', models.BooleanField(default=False)),
                ('in_response_to_tweet_id', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['brand', 'is_from_company'], name='supportagen_brand_d6046d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=64)),
                ('customer_text', models.TextField()),
                ('company_text', models.TextField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('company_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_company_reply', to='supportagent.tweet')),
                ('customer_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_customer_msg', to='supportagent.tweet')),
            ],
        ),
    ]
